### ISSUE TITLE
Potential resource: Publishing Python Packages

### ISSUE THREAD

**Issue by daneah** [pypackaging-native/pypackaging-native#13]
Hey folks, I didn't want to presume to open a pull request without discussing first:

Someone in my local community dev Slack channel sent the pypackaging-native project my way today as they saw a strong fit/overlap in goals with [_Publishing Python Packages_](https://pypackages.com) in teaching folks more about the ins and outs of the moving parts of packaging. I'd love for my book to be provided as a resource on the Resources page, naturally, and would be happy to contribute a pull request to that effect if you're open to it.

Let me know if I can answer any questions or help make the motivations and alignment more clear. I understand completely if you're just looking for freely available content (there are some freely available excerpts at the linked page), or if this just isn't aligned with your goals! Thanks for creating a community resource about this deep topic area. Let me know!

**Comment by rgommers** [comment]
Thanks for asking @daneah.  

> I understand completely if you're just looking for freely available content

I don't think that's required. _Only_ linking to non-free content doesn't seem like a good idea, however adding a link as one of a number of resources seems fine to me.

In this case, a section at the end of the Resources page about best resources to learning about Python packaging in general (rather than specific to native code) seems appropriate. It could list:
- https://packaging.python.org
- https://scikit-hep.org/developer/packaging
- your book
- ... what else?

**Comment by rgommers** [comment]
Nice suggestions, thanks - checked the ones I liked.
